x-bot-template: &bot-template
  restart: always
  working_dir: /app
  command: ["python", "-u", "bot.py"]
  environment:
    TZ: Europe/Paris           # ajuste si besoin
    PYTHONUNBUFFERED: "1"
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  autocontenuemmabot:
    <<: *bot-template
    build: ./autocontenuemmabot
    container_name: autocontenuemmabot
    volumes:
      - ./autocontenuemmabot:/app
      - ./autocontenuemmabot/session:/app/session
